# Generated by Django 4.2.4 on 2023-08-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'SHIPPED'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
